openapi: 3.0.0
paths:
  /health:
    get:
      operationId: AppController_health
      parameters: []
      responses:
        "200":
          description: ""
      tags:
        - App
  /auth/login:
    post:
      operationId: AuthController_login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginDto"
      responses:
        "201":
          description: ""
      tags:
        - Auth
  /user:
    get:
      operationId: UserController_getAllUsers
      parameters: []
      responses:
        "200":
          description: ""
      tags: &a1
        - User
    post:
      operationId: UserController_createUser
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDto"
      responses:
        "201":
          description: ""
      tags: *a1
  /user/{dni}:
    put:
      operationId: UserController_updateUser
      parameters:
        - name: dni
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDto"
      responses:
        "204":
          description: ""
      tags: *a1
    delete:
      operationId: UserController_deleteUser
      parameters:
        - name: dni
          required: true
          in: path
          schema:
            type: string
      responses:
        "204":
          description: ""
      tags: *a1
  /productionUnit:
    get:
      operationId: ProductionUnitController_getAllProductionUnits
      parameters: []
      responses:
        "200":
          description: ""
      tags: &a2
        - ProductionUnit
    post:
      operationId: ProductionUnitController_createProductionUnit
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductionUnitDto"
      responses:
        "201":
          description: ""
      tags: *a2
  /productionUnit/{name}:
    put:
      operationId: ProductionUnitController_updateProductionUnit
      parameters:
        - name: name
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductionUnitDto"
      responses:
        "204":
          description: ""
      tags: *a2
    delete:
      operationId: ProductionUnitController_deleteProductionUnit
      parameters:
        - name: name
          required: true
          in: path
          schema:
            type: string
      responses:
        "204":
          description: ""
      tags: *a2
  /supply:
    get:
      operationId: SupplyController_getAllSupply
      parameters: []
      responses:
        "200":
          description: ""
      tags: &a3
        - Supply
    post:
      operationId: SupplyController_createSupply
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SupplyDto"
      responses:
        "201":
          description: ""
      tags: *a3
  /supply/{name}:
    put:
      operationId: SupplyController_updateSupply
      parameters:
        - name: name
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SupplyDto"
      responses:
        "204":
          description: ""
      tags: *a3
    delete:
      operationId: SupplyController_deleteSupply
      parameters:
        - name: name
          required: true
          in: path
          schema:
            type: string
      responses:
        "204":
          description: ""
      tags: *a3
  /landFile:
    get:
      operationId: LandFileController_getAllLandFiles
      parameters: []
      responses:
        "200":
          description: ""
      tags: &a4
        - LandFile
    post:
      operationId: LandFileController_createLandFile
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LandFileDto"
      responses:
        "201":
          description: ""
      tags: *a4
  /landFile/{fileNumber}:
    put:
      operationId: LandFileController_updateLandFile
      parameters:
        - name: fileNumber
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LandFileDto"
      responses:
        "204":
          description: ""
      tags: *a4
    delete:
      operationId: LandFileController_deleteLandFile
      parameters:
        - name: fileNumber
          required: true
          in: path
          schema:
            type: string
      responses:
        "204":
          description: ""
      tags: *a4
  /producers:
    get:
      operationId: ProducerController_getAllProducers
      parameters: []
      responses:
        "200":
          description: ""
      tags: &a5
        - Producer
    post:
      operationId: ProducerController_createProducer
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProducerDto"
      responses:
        "201":
          description: ""
      tags: *a5
  /producers/{dni}:
    put:
      operationId: ProducerController_updateProducer
      parameters:
        - name: dni
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProducerDto"
      responses:
        "204":
          description: ""
      tags: *a5
    delete:
      operationId: ProducerController_deleteProducer
      parameters:
        - name: dni
          required: true
          in: path
          schema:
            type: string
      responses:
        "204":
          description: ""
      tags: *a5
info:
  title: NestJS Swagger
  description: API description
  version: "1.0"
  contact: {}
tags: []
servers: []
components:
  schemas:
    LoginDto:
      type: object
      properties: {}
    UserDto:
      type: object
      properties: {}
    ProductionUnitDto:
      type: object
      properties: {}
    SupplyDto:
      type: object
      properties: {}
    LandFileDto:
      type: object
      properties: {}
    ProducerDto:
      type: object
      properties: {}
