packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - '@compodoc/compodoc'
  - '@nestjs/core'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - esbuild
  - prisma
  - unrs-resolver
