pipeline {
    agent any

    stages{
         stage("tests") {
             steps {
                 echo 'Testing application'
             }
        }

        stage("build") {
            steps {
                echo 'Building application'
            }
        }

        stage("deploy") {
             steps {
                 echo 'Deploying application'
             }
        }
    }
}
